### ISSUE TITLE
TestClosed_WithoutLock

### ISSUE THREAD

**Issue by qqvvv** [6S9/c#1]
### 你有权保持沉默，但你所说的每一句话都将作为呈堂证供。
http://news.ifeng.com/a/20180326/57055763_0.shtml
![](http://p0.ifengimg.com/pmop/2018/0326/603965CCF04EC213A53E1F2F9F1239CBA92EB354_size30_w700_h690.jpeg)

**Comment by 6S9** [comment]
穷开心
https://m.bilibili.com/video/av19716936.html

**Comment by 6S9** [comment]
@ @ # #2

**Comment by 6S9** [comment]
#### 福娃设计者，手筋
### 申花，黄杨
>菜刀
>https://ss2.baidu.com/6ONYsjip0QIZ8tyhnq/it/u=2509131515,801903365&fm=175&s=1CAEC813A04103456606B7A50300700D&w=575&h=375&img.JPEG

**Comment by 6S9** [comment]
红啦
